apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    {{- include "class-schedule.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-endpoint: {{ .Values.backend.env.DB_ENDPOINT }}
  db-username: {{ .Values.backend.env.DB_USERNAME }}
  db-password: {{ .Values.backend.env.DB_PASSWORD }}
  redis-url: {{ .Values.backend.env.REDIS_URL }}