apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database-initdb
  labels:
    {{- include "class-schedule.labels" . | nindent 4 }}
data:
  dump.sql: |-
{{ .Files.Get .Values.database.restore.dumpFile | indent 4 }}