apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  labels:
    {{- include "class-schedule.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.database.credentials.username }}
  postgres-password: {{ .Values.database.credentials.password }}
  postgres-database: {{ .Values.database.credentials.database }}