apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    {{- include "class-schedule.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: 5432
    protocol: TCP
  selector:
    {{- include "class-schedule.selectorLabels" . | nindent 4 }}
    app: {{ .Release.Name }}-database